Don't show HTTP2 GoawayError in terminal
socketry/async-http pull request #65
Opened 2020-11-28 01:00 UTC by bruno-

Here's a minimal example that illustrates the problem:

```ruby
require "async"
require "async/http/internet"

Async do |task|
  internet = Async::HTTP::Internet.new
  puts internet.get("https://economist.com/").status # 301, HTTP2 connection
  task.sleep 10 # Protocol::HTTP2::GoawayError raised in ~5 seconds as the server closes the connection.

  puts "This code unexpectedly runs because the exception was only raised in the background."
  puts "The internet object is also fine."
  puts internet.get("https://economist.com/").status # 301
end
```
The problem is `Protocol::HTTP2::GoawayError` + its backtrace show up in the terminal whenever the remote server benevolently closes idle connection outside the request-response cycle.
The premise is: this scenario is not an error. It's equivalent to HTTP1 connection close after the request is done.

The current behavior looks like a scary issue (red characters in the terminal, stack trace etc), but it's not. In fact, `async-http` handles things great and there's nothing a user should do (like `rescue`, retry or similar).

I have not run an extensive research, but I think all the sites running http2 using amazon cloudfront or Incapsula/[imperva](https://www.imperva.com) do benevolently close idle http2 connections after 4 minutes. This maybe applies to other CDNs. Heres an example for site running on Incapsula CDN:

```ruby
require "async"
require "async/http/internet"

Async do |task|
  internet = Async::HTTP::Internet.new
  puts internet.get("https://www.proofpoint.com").read&.length
  task.sleep 250 # Protocol::HTTP2::GoawayError raised in 4 minutes
end
```

The proposal: don't show background task exception for `Protocol::HTTP2::GoawayError`.
I will add specs and improve the code if the idea is green-lighted.

## Types of Changes

- [x] Bug fix.
- [ ] New feature.
- [ ] Performance improvement.

## Testing

- [ ] I added new tests for my changes.
- [x] I ran all the tests locally.

2020-12-26 05:39 UTC, ioquatix requested changes

2020-12-26 05:39 UTC, ioquatix commented on lib/async/http/protocol/http2/connection.rb
> +							rescue ::Protocol::HTTP2::GoawayError => e
I am happy with this but please rename `e` to `error`.

2020-12-26 05:39 UTC, ioquatix commented
This seems fine to me and it's probably the right thing to do.

2020-12-27 21:20 UTC, bruno- commented
Feedback addressed.

2020-12-27 21:23 UTC, ioquatix approved these changes

2020-12-27 21:24 UTC, merged

2020-12-27 21:24 UTC, ioquatix commented
Thanks.